def write(doc, add_heading_1, add_heading_2, add_heading_3, add_p, add_bullet, add_code, style_table):
    add_heading_1("CHƯƠNG 2. CƠ SỞ LÝ THUYẾT")

    add_heading_2("2.1. Tổng quan về Bài toán Tóm tắt văn bản (Text Summarization)")
    add_p("Tóm tắt văn bản tự động (Automatic Text Summarization - ATS) là một quá trình ứng dụng các thuật toán phân tích, học máy và xử lý ngôn ngữ tự nhiên (NLP) nhằm cô đọng một hay nhiều văn bản gốc thành một phiên bản ngắn gọn hơn rất nhiều. Mục tiêu tối thượng của bài toán này không chỉ là cắt xén cơ học, mà là phải bảo tồn một cách hoàn hảo các thông tin quan trọng nhất, các sự kiện cốt lõi (thực thể, con số, địa danh) và giữ vững tính logic xuyên suốt của ngữ nghĩa gốc.")
    add_p("Sự ra đời của bài toán này xuất phát từ nhu cầu cấp thiết trong việc giải quyết hiện tượng \"Quá tải thông tin\" (Information Overload) của kỷ nguyên số. Hằng ngày, lượng tài liệu điện tử, báo cáo tài chính, và các bài báo tin tức được sản sinh ra là khổng lồ. Khác với con người có khả năng đọc hiểu, chắt lọc và diễn đạt lại ý chính một cách tự nhiên dựa trên trí tuệ và kiến thức nền tảng (background knowledge), việc dạy cho máy tính hiểu thế nào là \"quan trọng\" là một thách thức toán học và kỹ thuật cực kỳ phức tạp.")
    add_p("Để thực hiện tóm tắt, máy tính phải vượt qua hàng loạt rào cản đặc thù của ngôn ngữ tự nhiên. Chúng bao gồm việc xử lý từ đồng nghĩa (synonyms), hiện tượng đa nghĩa (polysemy), cấu trúc ngữ pháp phức hợp, hiện tượng đồng tham chiếu (coreference resolution - ví dụ: từ \"ông ấy\" đang chỉ ai trong câu trước), và loại bỏ các thông tin dư thừa, các lời dẫn dắt không mang ý nghĩa lõi.")
    add_p("Trong thực tiễn thương mại và học thuật, các hệ thống tóm tắt văn bản hiện đại đang đóng vai trò làm trái tim cho các công cụ máy tìm kiếm (Search Engines), các nền tảng tổng hợp tin tức tự động (News Aggregators), và các hệ thống hỗ trợ trích xuất thông tin y tế, tài chính pháp luật. Chúng giúp giải phóng con người khỏi hàng triệu giờ lao động thủ công mỗi ngày, đẩy nhanh tốc độ tiêu thụ tri thức và nâng cao hiệu suất ra quyết định.")

    add_heading_2("2.2. Phân loại Bài toán Tóm tắt: Trích xuất (Extractive) và Sinh (Abstractive)")
    add_bullet("Extractive Summarization (Tóm tắt Trích xuất): Thuật toán sẽ quét qua toàn bộ các câu, tính toán điểm số tầm quan trọng (Importance Score), và \"trích xuất\" nguyên văn các câu đạt điểm cao nhất để ghép lại. Ưu điểm: Đảm bảo 100% tính chính xác sự thật (Factuality), không bịa đặt (Zero Hallucination).")
    add_bullet("Abstractive Summarization (Tóm tắt Sinh nội dung): Mô hình đọc hiểu toàn bộ văn bản và sinh ra các câu mới hoàn toàn từ đầu. Nhược điểm chí mạng là chi phí tính toán cực kỳ tốn kém và nguy cơ rất cao mắc phải hiện tượng Hallucination (tự bịa sự kiện, con số).")
    add_p("Chính nhờ khả năng bảo toàn nguyên vẹn 100% độ chính xác của các sự kiện, con số và phát ngôn gốc (Factuality) mà không bao giờ mắc phải hiện tượng 'ảo giác' (Hallucination), phương pháp Tóm tắt Trích xuất (Extractive) luôn mang lại sự tin cậy tuyệt đối, trở thành lựa chọn hàng đầu được các tòa soạn báo, cơ quan pháp lý và độc giả ưa chuộng hơn hẳn so với các mô hình Sinh nội dung (Abstractive) - vốn luôn ẩn chứa rủi ro sai lệch thông tin nghiêm trọng.")

    add_heading_2("2.3. Kiến trúc Đột phá Transformer")
    add_p("Năm 2017, bài báo lịch sử \"Attention Is All You Need\" (Vaswani et al.) [15] đánh dấu sự ra đời của Transformer. Trước đó, các mô hình RNN (như LSTM, GRU) xử lý tuần tự (từng từ một) nên rất chậm và khó nhớ ngữ cảnh xa. Transformer khắc phục triệt để bằng cách thay thế hoàn toàn mạng hồi quy bằng cơ chế Tự chú ý (Self-Attention), cho phép khả năng song song hóa toàn diện.")
    add_p("Kiến trúc Transformer gồm 2 phần chính:")
    add_bullet("Encoder (Bộ mã hóa): Nhận câu đầu vào và chuyển thành vector ngữ nghĩa. Mục tiêu là đọc hiểu văn bản.")
    add_bullet("Decoder (Bộ giải mã): Nhận vector ngữ nghĩa và sinh ra từng từ một để tạo thành câu đầu ra. Mục tiêu là sinh văn bản.")
    
    add_heading_3("2.3.1. Cơ chế Self-Attention và Multi-Head Attention")
    add_p("Self-Attention cho phép mỗi từ trong câu đánh giá mức độ tương quan của nó với tất cả các từ khác cùng lúc. Toán học của Self-Attention xoay quanh 3 ma trận Q (Query), K (Key), V (Value):")
    add_code("Attention(Q, K, V) = softmax( (Q . K^T) / sqrt(d_k) ) . V")
    add_p("Thay vì dùng 1 hàm Attention, Transformer sử dụng Multi-head Attention chia vector ra thành H \"đầu\" (Heads) độc lập (thường là 8 head). Mỗi head học một đặc trưng ngữ nghĩa riêng biệt, sau đó nối lại (Concat) và nhân với ma trận trọng số cuối.")

    add_heading_3("2.3.2. Cấu trúc Luồng dữ liệu bên trong Encoder")
    add_p("Trước khi văn bản thực sự bước vào các khối Encoder, mỗi token đầu vào sẽ được ánh xạ thành một vector 768 chiều (đối với bản base). Vector khởi thủy này thực chất là phép cộng ma trận (element-wise addition) của 3 thành phần: (1) Token Embedding (mang ý nghĩa từ vựng), (2) Positional Embedding (đánh dấu vị trí thứ tự của từ trong câu), và (3) Segment Embedding. (Lưu ý sắc bén: Trong kiến trúc BERT gốc, Segment Embedding dùng để phân biệt câu A và câu B trong cùng một lượt. Nhưng vì Đồ án sử dụng SBERT - kiến trúc Bi-Encoder xử lý độc lập từng câu một, nên Segment Embedding thực chất trở thành một hằng số [0] vô hiệu hóa, giúp tăng tốc độ tính toán).")
    add_p("Mỗi lớp Encoder tiếp tục bao gồm các bước xử lý tinh vi: (1) Multi-head Self-attention để lấy ngữ cảnh. (2) Residual connection + LayerNorm để chống mất mát thông tin ban đầu. (3) Feed-forward network (ReLU) để trải phẳng và nén dữ liệu. (4) Tiếp tục Residual + LayerNorm. Mô hình tiêu biểu sử dụng toàn Encoder là BERT, RoBERTa.")

    add_heading_2("2.4. Mô hình Ngôn ngữ Hai chiều BERT (2018)")
    add_p("Năm 2018, BERT (Bidirectional Encoder Representations from Transformers) ra đời bằng cách xếp chồng các lớp Encoder của Transformer. Khác biệt cốt lõi là BERT học hai chiều (bidirectional) thông qua 2 tác vụ tiền huấn luyện: Masked Language Model (MLM - che đi một số từ và đoán lại) và Next Sentence Prediction (NSP - dự đoán 2 câu có liên tiếp không).")
    
    add_heading_2("2.5. Vấn đề Dị hướng (Anisotropy) của BERT")
    add_p("Khi áp dụng BERT vào bài toán so sánh độ tương đồng 2 câu, nếu ghép 2 câu lại thành chuỗi [CLS] Câu A [SEP] Câu B [SEP] (Cross-Encoder), BERT cho độ chính xác cực cao nhưng cực kỳ chậm. Nếu đem N=10,000 câu đi so sánh với nhau, BERT phải chạy qua mạng Neural 49.995.000 lần (mất 65 giờ).")
    add_p("Để nhanh hơn, người ta thử rút trích độc lập từng vector của câu (lấy tại token [CLS] hoặc tính MEAN tất cả các token) rồi tính Cosine Similarity. Tuy nhiên, kết quả lại tệ hại hơn cả mô hình GloVe cổ điển (theo điểm Spearman) [5]. Nguyên nhân là do Không gian vector của BERT bị mắc hội chứng Dị hướng (Anisotropy) [2]. Các vector không phân bố đều mà bị dồn ép vào một góc hẹp (hình nón dương). Hậu quả là tính Cosine giữa 2 câu ngẫu nhiên bất kỳ luôn ra điểm rất cao (0.8 - 0.9), khiến máy tính không thể phân biệt được câu giống và câu khác nhau.")

    add_heading_2("2.6. Giải pháp Đột phá: Sentence-BERT (Bi-Encoder)")
    add_p("Năm 2019, SBERT (Reimers & Gurevych) [5] ra đời nhằm giải quyết đồng thời hai điểm yếu chí mạng của BERT gốc: Nút thắt cổ chai về Tốc độ tính toán và Hội chứng Dị hướng (Anisotropy). Lời giải của SBERT đến từ hai đột phá song song: Thay đổi Kiến trúc và Thay đổi Phương pháp Huấn luyện.")
    add_bullet("Đột phá Kiến trúc (Giải quyết Tốc độ): SBERT sử dụng mạng Siamese (Mạng anh em sinh đôi) kết hợp cùng Lớp toán gộp (Pooling Layer). Thay vì nạp 2 câu vào mạng Neural cùng lúc, SBERT mã hóa độc lập từng câu thành một vector kích thước cố định. Thiết kế Bi-Encoder này cho phép tính toán trước (Pre-compute) vector của hàng triệu câu, qua đó giảm thời gian tìm kiếm từ 65 giờ xuống chỉ còn 5 giây.", bold_prefix="1. ")
    add_bullet("Đột phá Huấn luyện (Giải quyết Dị hướng): Nếu chỉ thay đổi kiến trúc, chất lượng vector sinh ra vẫn rất tệ. Đóng góp cốt lõi của SBERT là quy trình Tinh chỉnh (Siamese Fine-tuning) trên tập dữ liệu NLI và STS. Thông qua Hàm mất mát tương phản (Contrastive Loss), mạng Neural bị ép phải nắn lại không gian hình học: kéo các vector đồng nghĩa lại gần nhau và đẩy các vector trái nghĩa ra xa. Quá trình này tạo ra một không gian vector đồng nhất (Isotropic), giúp phép đo Cosine Similarity trở nên cực kỳ chuẩn xác.", bold_prefix="2. ")
    add_heading_3("2.6.1. Lớp Toán gộp (Pooling Layer) và Xử lý Độ dài Câu")
    add_p("Về mặt kiến trúc, SBERT thừa hưởng giới hạn đầu vào của BERT là tối đa 512 tokens. Các câu ngắn hơn sẽ được chèn thêm token đệm ([PAD]), các câu dài hơn 512 tokens sẽ bị cắt cụt (truncate).")
    add_p("Đầu ra của BERT là một chuỗi các vector tương ứng với số lượng từ. Để giải quyết bài toán: 'Làm sao 2 câu có độ dài khác nhau lại có thể so sánh được với nhau?', SBERT tích hợp thêm Lớp Pooling ngay sau đầu ra của BERT để tính toán và cô đặc N vector (mỗi vector 768 chiều) thành chính xác 1 vector duy nhất (768 chiều). Nhóm tác giả thử nghiệm 3 chiến lược:")
    add_bullet("CLS-token: Chỉ lấy vector tại token [CLS]. Tuy nhiên, do token này vốn bị 'thiên kiến' (bias) bởi tác vụ Next Sentence Prediction trong quá trình pre-train của BERT, nó không đại diện tốt cho toàn bộ ý nghĩa của câu.")
    add_bullet("MAX Pooling: Lấy giá trị lớn nhất theo từng chiều không gian. Dù phát hiện từ khóa (keywords) tốt, chiến lược này làm vỡ cấu trúc ngữ cảnh của câu.")
    add_bullet("MEAN Pooling: Tính trung bình cộng tất cả vector token dựa trên chiều dài thực tế L của từng câu. Sử dụng Attention Mask để phớt lờ hoàn toàn các token đệm [PAD], nhờ đó biến L thành một tham số biến thiên (tùy thuộc vào số từ thật của mỗi câu) thay vì chia mù quáng cho max_length. Khi tính trung bình, các nhiễu tự triệt tiêu, để lại phần ngữ nghĩa cốt lõi nhất. Đây là chiến lược mặc định mang lại hiệu năng cao nhất trên mọi tập dữ liệu và cũng là cấu hình được sử dụng để tinh chỉnh mô hình Tiếng Việt trong Đồ án này.")

    add_heading_3("2.6.2. Các Hàm mục tiêu Huấn luyện (Objective Functions)")
    add_p("Quá trình huấn luyện đặc biệt này đã \"ép\" không gian vector của mô hình phải bung tỏa đều ra mọi hướng, nắn lại hình học không gian. Tùy vào loại dữ liệu, SBERT sử dụng 3 hàm mục tiêu:")
    add_bullet("a. Hàm mục tiêu Phân loại (Classification Objective): Sử dụng khi dữ liệu có nhãn hạng mục (ví dụ: mâu thuẫn, đồng thuận). SBERT trích 2 vector u, v, sau đó thực hiện phép nối (Concatenation): [u, v, |u - v|]. Thành phần |u - v| cực kỳ quan trọng vì nó trực tiếp đo lường khoảng cách hình học.")
    add_bullet("b. Hàm mục tiêu Hồi quy (Regression Objective): Dùng cho dữ liệu chấm điểm liên tục (ví dụ: điểm tương đồng 0-5). SBERT tính trực tiếp Cosine(u,v) và dùng hàm Mean-Squared-Error (MSE) để tối thiểu sai số.")
    add_bullet("c. Hàm mục tiêu Triplet (Triplet Objective): Nhận đầu vào 3 câu: Câu neo (Anchor a), Câu dương tính đồng nghĩa (Positive p), Câu âm tính khác nghĩa (Negative n). Hàm Triplet Loss tinh chỉnh mạng lưới sao cho khoảng cách Euclid ||a - p|| phải luôn nhỏ hơn ||a - n|| cộng thêm một khoảng biên an toàn (epsilon). Hàm này thể hiện rõ nhất cơ chế 'kéo gần, đẩy xa' trong học sâu.")

    add_heading_2("2.7. Đánh đổi giữa Tốc độ và Độ chính xác (Cross-Encoder vs Bi-Encoder)")
    add_p("Trong thiết kế hệ thống AI thực tế, luôn có sự đánh đổi (Trade-off) giữa Tốc độ và Độ chính xác:")
    add_bullet("Cross-Encoder (BERT): Ghép 2 câu lại với nhau ([CLS] Câu A [SEP] Câu B [SEP]). Nhờ cơ chế cross-attention, từ của 2 câu tương tác chéo với nhau ngay từ lớp mạng đầu tiên -> Độ chính xác hoàn hảo nhưng cực kỳ CHẬM.")
    add_bullet("Bi-Encoder (SBERT): Đưa từng câu vào mô hình một cách độc lập để trích xuất Embedding. Hai câu bị cô lập và chỉ tương tác ở phép tính khoảng cách Euclid hoặc Cosine cuối cùng -> Mất mát một phần thông tin nhưng cực kỳ NHANH.")
    
    add_heading_3("2.7.1. Định hướng Ứng dụng SBERT trong Tóm tắt Văn bản")
    add_p("Trong khuôn khổ Đồ án, hệ thống Tóm tắt văn bản vận hành theo cơ chế Bi-Encoder. SBERT không được dùng để so sánh trực tiếp cặp câu nào. Thay vào đó, giả sử bài báo có N câu, hệ thống sẽ bơm lần lượt N câu này vào SBERT để trích xuất ra N vector nhúng 768 chiều một cách hoàn toàn độc lập. Quá trình so sánh, tìm điểm tương đồng và phân nhóm ngữ nghĩa được đẩy hoàn toàn ra bên ngoài mạng Neural, giao cho thuật toán Phân cụm K-Means đảm nhiệm. Cách tiếp cận này giúp hệ thống tóm tắt tức thời chỉ trong vài mili-giây, vượt qua hoàn toàn nút thắt cổ chai về mặt hiệu năng của BERT.")

def write(doc, add_heading_1, add_heading_2, add_heading_3, add_p, add_bullet, add_code, style_table):
    add_heading_1("CHƯƠNG 2. CƠ SỞ LÝ THUYẾT")

    add_heading_2("2.1. Tổng quan về Bài toán Tóm tắt văn bản (Text Summarization)")
    add_p("Tóm tắt văn bản tự động (Automatic Text Summarization - ATS) là một quá trình ứng dụng các thuật toán phân tích, học máy và xử lý ngôn ngữ tự nhiên (NLP) nhằm cô đọng một hay nhiều văn bản gốc thành một phiên bản ngắn gọn hơn rất nhiều. Mục tiêu tối thượng của bài toán này không chỉ là cắt xén cơ học, mà là phải bảo tồn một cách hoàn hảo các thông tin quan trọng nhất, các sự kiện cốt lõi (thực thể, con số, địa danh) và giữ vững tính logic xuyên suốt của ngữ nghĩa gốc.")
    add_p("Sự ra đời của bài toán này xuất phát từ nhu cầu cấp thiết trong việc giải quyết hiện tượng \"Quá tải thông tin\" (Information Overload) của kỷ nguyên số. Hằng ngày, lượng tài liệu điện tử, báo cáo tài chính, và các bài báo tin tức được sản sinh ra là khổng lồ. Khác với con người có khả năng đọc hiểu, chắt lọc và diễn đạt lại ý chính một cách tự nhiên dựa trên trí tuệ và kiến thức nền tảng (background knowledge), việc dạy cho máy tính hiểu thế nào là \"quan trọng\" là một thách thức toán học và kỹ thuật cực kỳ phức tạp.")
    add_p("Để thực hiện tóm tắt, máy tính phải vượt qua hàng loạt rào cản đặc thù của ngôn ngữ tự nhiên. Chúng bao gồm việc xử lý từ đồng nghĩa (synonyms), hiện tượng đa nghĩa (polysemy), cấu trúc ngữ pháp phức hợp, hiện tượng đồng tham chiếu (coreference resolution - ví dụ: từ \"ông ấy\" đang chỉ ai trong câu trước), và loại bỏ các thông tin dư thừa, các lời dẫn dắt không mang ý nghĩa lõi.")
    add_p("Trong thực tiễn thương mại và học thuật, các hệ thống tóm tắt văn bản hiện đại đang đóng vai trò làm trái tim cho các công cụ máy tìm kiếm (Search Engines), các nền tảng tổng hợp tin tức tự động (News Aggregators), và các hệ thống hỗ trợ trích xuất thông tin y tế, tài chính pháp luật. Chúng giúp giải phóng con người khỏi hàng triệu giờ lao động thủ công mỗi ngày, đẩy nhanh tốc độ tiêu thụ tri thức và nâng cao hiệu suất ra quyết định.")

    add_heading_2("2.2. Phân loại Bài toán Tóm tắt: Trích xuất (Extractive) và Sinh (Abstractive)")
    add_bullet("Extractive Summarization (Tóm tắt Trích xuất): Thuật toán sẽ quét qua toàn bộ các câu, tính toán điểm số tầm quan trọng (Importance Score), và \"trích xuất\" nguyên văn các câu đạt điểm cao nhất để ghép lại. Ưu điểm: Đảm bảo 100% tính chính xác sự thật (Factuality), không bịa đặt (Zero Hallucination).")
    add_bullet("Abstractive Summarization (Tóm tắt Sinh nội dung): Mô hình đọc hiểu toàn bộ văn bản và sinh ra các câu mới hoàn toàn từ đầu. Nhược điểm chí mạng là chi phí tính toán cực kỳ tốn kém và nguy cơ rất cao mắc phải hiện tượng Hallucination (tự bịa sự kiện, con số).")
    add_p("Chính nhờ khả năng bảo toàn nguyên vẹn 100% độ chính xác của các sự kiện, con số và phát ngôn gốc (Factuality) mà không bao giờ mắc phải hiện tượng 'ảo giác' (Hallucination), phương pháp Tóm tắt Trích xuất (Extractive) luôn mang lại sự tin cậy tuyệt đối, trở thành lựa chọn hàng đầu được các tòa soạn báo, cơ quan pháp lý và độc giả ưa chuộng hơn hẳn so với các mô hình Sinh nội dung (Abstractive) - vốn luôn ẩn chứa rủi ro sai lệch thông tin nghiêm trọng.")

    add_heading_2("2.3. Kiến trúc Đột phá Transformer")
    add_p("Năm 2017, bài báo lịch sử \"Attention Is All You Need\" (Vaswani et al.) [15] đánh dấu sự ra đời của Transformer. Trước đó, các mô hình RNN (như LSTM, GRU) xử lý tuần tự (từng từ một) nên rất chậm và khó nhớ ngữ cảnh xa. Transformer khắc phục triệt để bằng cách thay thế hoàn toàn mạng hồi quy bằng cơ chế Tự chú ý (Self-Attention), cho phép khả năng song song hóa toàn diện.")
    add_p("Kiến trúc Transformer gồm 2 phần chính:")
    add_bullet("Encoder (Bộ mã hóa): Nhận câu đầu vào và chuyển thành vector ngữ nghĩa. Mục tiêu là đọc hiểu văn bản.")
    add_bullet("Decoder (Bộ giải mã): Nhận vector ngữ nghĩa và sinh ra từng từ một để tạo thành câu đầu ra. Mục tiêu là sinh văn bản.")
    
    add_heading_3("2.3.1. Cơ chế Self-Attention và Multi-Head Attention")
    add_p("Self-Attention cho phép mỗi từ trong câu đánh giá mức độ tương quan của nó với tất cả các từ khác cùng lúc. Toán học của Self-Attention xoay quanh 3 ma trận Q (Query), K (Key), V (Value):")
    add_code("Attention(Q, K, V) = softmax( (Q . K^T) / sqrt(d_k) ) . V")
    add_p("Thay vì dùng 1 hàm Attention, Transformer sử dụng Multi-head Attention chia vector ra thành H \"đầu\" (Heads) độc lập (thường là 8 head). Mỗi head học một đặc trưng ngữ nghĩa riêng biệt, sau đó nối lại (Concat) và nhân với ma trận trọng số cuối.")

    add_heading_3("2.3.2. Cấu trúc Luồng dữ liệu bên trong Encoder")
    add_p("Trước khi văn bản thực sự bước vào các khối Encoder, mỗi token đầu vào sẽ được ánh xạ thành một vector 768 chiều (đối với bản base). Vector khởi thủy này thực chất là phép cộng ma trận (element-wise addition) của 3 thành phần: (1) Token Embedding (mang ý nghĩa từ vựng), (2) Positional Embedding (đánh dấu vị trí thứ tự của từ trong câu), và (3) Segment Embedding. (Lưu ý sắc bén: Trong kiến trúc BERT gốc, Segment Embedding dùng để phân biệt câu A và câu B trong cùng một lượt. Nhưng vì Đồ án sử dụng SBERT - kiến trúc Bi-Encoder xử lý độc lập từng câu một, nên Segment Embedding thực chất trở thành một hằng số [0] vô hiệu hóa, giúp tăng tốc độ tính toán).")
    add_p("Mỗi lớp Encoder tiếp tục bao gồm các bước xử lý tinh vi: (1) Multi-head Self-attention để lấy ngữ cảnh. (2) Residual connection + LayerNorm để chống mất mát thông tin ban đầu. (3) Feed-forward network (ReLU) để trải phẳng và nén dữ liệu. (4) Tiếp tục Residual + LayerNorm. Mô hình tiêu biểu sử dụng toàn Encoder là BERT, RoBERTa.")

    add_heading_2("2.4. Mô hình Ngôn ngữ Hai chiều BERT (2018)")
    add_p("Năm 2018, BERT (Bidirectional Encoder Representations from Transformers) ra đời bằng cách xếp chồng các lớp Encoder của Transformer. Khác biệt cốt lục là BERT học hai chiều (bidirectional) thông qua 2 tác vụ tiền huấn luyện: Masked Language Model (MLM - che đi một số từ và đoán lại) và Next Sentence Prediction (NSP - dự đoán 2 câu có liên tiếp không).")
    
    add_heading_2("2.5. Vấn đề Dị hướng (Anisotropy) của BERT")
    add_p("Khi áp dụng BERT vào bài toán so sánh độ tương đồng 2 câu, nếu ghép 2 câu lại thành chuỗi [CLS] Câu A [SEP] Câu B [SEP] (Cross-Encoder), BERT cho độ chính xác cực cao nhưng cực kỳ chậm. Nếu đem N=10,000 câu đi so sánh với nhau, BERT phải chạy qua mạng Neural 49.995.000 lần (mất 65 giờ).")
    add_p("Để nhanh hơn, người ta thử rút trích độc lập từng vector của câu (lấy tại token [CLS] hoặc tính MEAN tất cả các token) rồi tính Cosine Similarity. Tuy nhiên, kết quả lại tệ hại hơn cả mô hình GloVe cổ điển (theo điểm Spearman) [5]. Nguyên nhân là do Không gian vector của BERT bị mắc hội chứng Dị hướng (Anisotropy) [2]. Các vector không phân bố đều mà bị dồn ép vào một góc hẹp (hình nón dương). Hậu quả là tính Cosine giữa 2 câu ngẫu nhiên bất kỳ luôn ra điểm rất cao (0.8 - 0.9), khiến máy tính không thể phân biệt được câu giống và câu khác nhau.")

    add_heading_2("2.6. Giải pháp Đột phá: Sentence-BERT (Bi-Encoder)")
    add_p("Năm 2019, SBERT (Reimers & Gurevych) [5] ra đời nhằm giải quyết đồng thời hai điểm yếu chí mạng của BERT gốc: Nút thắt cổ chai về Tốc độ tính toán và Hội chứng Dị hướng (Anisotropy). Lời giải của SBERT đến từ hai đột phá song song: Thay đổi Kiến trúc và Thay đổi Phương pháp Huấn luyện.")
    add_bullet("Đột phá Kiến trúc (Giải quyết Tốc độ): SBERT sử dụng mạng Siamese (Mạng anh em sinh đôi) kết hợp cùng Lớp toán gộp (Pooling Layer). Thay vì nạp 2 câu vào mạng Neural cùng lúc, SBERT mã hóa độc lập từng câu thành một vector kích thước cố định. Thiết kế Bi-Encoder này cho phép tính toán trước (Pre-compute) vector của hàng triệu câu, qua đó giảm thời gian tìm kiếm từ 65 giờ xuống chỉ còn 5 giây.", bold_prefix="1. ")
    add_bullet("Đột phá Huấn luyện (Giải quyết Dị hướng): Nếu chỉ thay đổi kiến trúc, chất lượng vector sinh ra vẫn rất tệ. Đóng góp cốt lõi của SBERT là quy trình Tinh chỉnh (Siamese Fine-tuning) trên tập dữ liệu NLI và STS. Thông qua Hàm mất mát tương phản (Contrastive Loss), mạng Neural bị ép phải nắn lại không gian hình học: kéo các vector đồng nghĩa lại gần nhau và đẩy các vector trái nghĩa ra xa. Quá trình này tạo ra một không gian vector đồng nhất (Isotropic), giúp phép đo Cosine Similarity trở nên cực kỳ chuẩn xác.", bold_prefix="2. ")
    add_heading_3("2.6.1. Lớp Toán gộp (Pooling Layer) và Xử lý Độ dài Câu")
    add_p("Về mặt kiến trúc, SBERT thừa hưởng giới hạn đầu vào của BERT là tối đa 512 tokens. Các câu ngắn hơn sẽ được chèn thêm token đệm ([PAD]), các câu dài hơn 512 tokens sẽ bị cắt cụt (truncate).")
    add_p("Đầu ra của BERT là một chuỗi các vector tương ứng với số lượng từ. Để giải quyết bài toán: 'Làm sao 2 câu có độ dài khác nhau lại có thể so sánh được với nhau?', SBERT tích hợp thêm Lớp Pooling ngay sau đầu ra của BERT để tính toán và cô đặc N vector (mỗi vector 768 chiều) thành chính xác 1 vector duy nhất (768 chiều). Nhóm tác giả thử nghiệm 3 chiến lược:")
    add_bullet("CLS-token: Chỉ lấy vector tại token [CLS]. Tuy nhiên, do token này vốn bị 'thiên kiến' (bias) bởi tác vụ Next Sentence Prediction trong quá trình pre-train của BERT, nó không đại diện tốt cho toàn bộ ý nghĩa của câu.")
    add_bullet("MAX Pooling: Lấy giá trị lớn nhất theo từng chiều không gian. Dù phát hiện từ khóa (keywords) tốt, chiến lược này làm vỡ cấu trúc ngữ cảnh của câu.")
    add_bullet("MEAN Pooling: Tính trung bình cộng tất cả vector token dựa trên chiều dài thực tế L của từng câu. Sử dụng Attention Mask để phớt lờ hoàn toàn các token đệm [PAD], nhờ đó biến L thành một tham số biến thiên (tùy thuộc vào số từ thật của mỗi câu) thay vì chia mù quáng cho max_length. Khi tính trung bình, các nhiễu tự triệt tiêu, để lại phần ngữ nghĩa cốt lõi nhất. Đây là chiến lược mặc định mang lại hiệu năng cao nhất trên mọi tập dữ liệu và cũng là cấu hình được sử dụng để tinh chỉnh mô hình Tiếng Việt trong Đồ án này.")

    add_heading_3("2.6.2. Các Hàm mục tiêu Huấn luyện (Objective Functions)")
    add_p("Quá trình huấn luyện đặc biệt này đã \"ép\" không gian vector của mô hình phải bung tỏa đều ra mọi hướng, nắn lại hình học không gian. Tùy vào loại dữ liệu, SBERT sử dụng 3 hàm mục tiêu:")
    add_bullet("a. Hàm mục tiêu Phân loại (Classification Objective): Sử dụng khi dữ liệu có nhãn hạng mục (ví dụ: mâu thuẫn, đồng thuận). SBERT trích 2 vector u, v, sau đó thực hiện phép nối (Concatenation): [u, v, |u - v|]. Thành phần |u - v| cực kỳ quan trọng vì nó trực tiếp đo lường khoảng cách hình học.")
    add_bullet("b. Hàm mục tiêu Hồi quy (Regression Objective): Dùng cho dữ liệu chấm điểm liên tục (ví dụ: điểm tương đồng 0-5). SBERT tính trực tiếp Cosine(u,v) và dùng hàm Mean-Squared-Error (MSE) để tối thiểu sai số.")
    add_bullet("c. Hàm mục tiêu Triplet (Triplet Objective): Nhận đầu vào 3 câu: Câu neo (Anchor a), Câu dương tính đồng nghĩa (Positive p), Câu âm tính khác nghĩa (Negative n). Hàm Triplet Loss tinh chỉnh mạng lưới sao cho khoảng cách Euclid ||a - p|| phải luôn nhỏ hơn ||a - n|| cộng thêm một khoảng biên an toàn (epsilon). Hàm này thể hiện rõ nhất cơ chế 'kéo gần, đẩy xa' trong học sâu.")

    add_heading_2("2.7. Đánh đổi giữa Tốc độ và Độ chính xác (Cross-Encoder vs Bi-Encoder)")
    add_p("Trong thiết kế hệ thống AI thực tế, luôn có sự đánh đổi (Trade-off) giữa Tốc độ và Độ chính xác:")
    add_bullet("Cross-Encoder (BERT): Ghép 2 câu lại với nhau ([CLS] Câu A [SEP] Câu B [SEP]). Nhờ cơ chế cross-attention, từ của 2 câu tương tác chéo với nhau ngay từ lớp mạng đầu tiên -> Độ chính xác hoàn hảo nhưng cực kỳ CHẬM.")
    add_bullet("Bi-Encoder (SBERT): Đưa từng câu vào mô hình một cách độc lập để trích xuất Embedding. Hai câu bị cô lập và chỉ tương tác ở phép tính khoảng cách Euclid hoặc Cosine cuối cùng -> Mất mát một phần thông tin nhưng cực kỳ NHANH.")
    
    add_heading_3("2.7.1. Định hướng Ứng dụng SBERT trong Tóm tắt Văn bản")
    add_p("Trong khuôn khổ Đồ án, hệ thống Tóm tắt văn bản vận hành theo cơ chế Bi-Encoder. SBERT không được dùng để so sánh trực tiếp cặp câu nào. Thay vào đó, giả sử bài báo có N câu, hệ thống sẽ bơm lần lượt N câu này vào SBERT để trích xuất ra N vector nhúng 768 chiều một cách hoàn toàn độc lập. Quá trình so sánh, tìm điểm tương đồng và phân nhóm ngữ nghĩa được đẩy hoàn toàn ra bên ngoài mạng Neural, giao cho thuật toán Phân cụm K-Means đảm nhiệm. Cách tiếp cận này giúp hệ thống tóm tắt tức thời chỉ trong vài mili-giây, vượt qua hoàn toàn nút thắt cổ chai về mặt hiệu năng của BERT.")

    add_heading_3("2.8.2. Giải quyết Đặc thù Tiếng Việt")
    add_p("Tiếng Việt là ngôn ngữ đơn lập, âm tiết rời rạc. Nếu dùng Tokenizer Tiếng Anh, từ \"Trí tuệ nhân tạo\" sẽ bị xé nát. Nhằm giải quyết triệt để vấn đề này, hệ thống áp dụng chiến thuật xử lý kép (Dual-Processing):")
    add_bullet("1. Tách Câu (Sentence Tokenization): Sử dụng thư viện AI 'underthesea' ở bước Tiền xử lý (Preprocessing). Thay vì cắt câu mù quáng bằng dấu chấm, underthesea có khả năng nhận diện các từ viết tắt chuyên ngành (TS., T.P., v.v.), đảm bảo câu văn không bị cắt vụn sai ngữ pháp trước khi nạp vào hệ thống.")
    add_bullet("2. Tách Từ (Word Segmentation) & Mã hóa: Sử dụng mô hình Vietnamese Bi-Encoder (bkai-foundation-models) được tích hợp sẵn bộ Tokenizer thuật toán SentencePiece. Thuật toán này có khả năng trực tiếp đọc văn bản Tiếng Việt thô (Raw text) và tự động ánh xạ các cụm từ ghép mà không cần bước gạch dưới (underscore) thủ công, giúp tối ưu hóa toàn diện tốc độ và độ chính xác của hệ thống.")

    add_heading_2("2.9. Khung Chỉ số Đánh giá Kép (Dual-Evaluation Framework)")
    add_bullet("ROUGE (Recall-Oriented Understudy for Gisting Evaluation) [9]: Đánh giá độ trùng lặp n-gram thông qua 3 thước đo: ROUGE-1 (Unigram), ROUGE-2 (Bigram), và ROUGE-L (LCS - Chuỗi con chung dài nhất). Trong mã nguồn, nhóm sử dụng hàm fmeasure để lấy điểm ROUGE-F1 làm tiêu chuẩn đánh giá trung hòa:", "Chỉ số Ngoại tại (Extrinsic): ")
    add_code(r"F_1 = 2 \times \frac{\text{Precision} \times \text{Recall}}{\text{Precision} + \text{Recall}}")
    add_bullet("Semantic BERTScore [10]: Đo lường độ tương đồng ngữ nghĩa cấp độ vector, khắc phục nhược điểm 'học vẹt' từ vựng của ROUGE. Nhóm lập trình hàm tính toán bằng cách trích xuất Vector của toàn bộ Bản tóm tắt và Bản gốc thông qua SBERT Fine-Tuned, sau đó tính khoảng cách góc:", "Chỉ số Ngoại tại (Extrinsic): ")
    add_code(r"\text{BERTScore}_{F1} = \cos(\mathbf{v}_{sum}, \mathbf{v}_{ref}) = \frac{\mathbf{v}_{sum} \cdot \mathbf{v}_{ref}}{\|\mathbf{v}_{sum}\| \|\mathbf{v}_{ref}\|}")
    add_bullet("Compression Ratio (Tỷ lệ nén) [16]: Đo lường hiệu quả cô đặc thông tin, đảm bảo bản tóm tắt không quá dài so với bài báo gốc:", "Chỉ số Ngoại tại (Extrinsic): ")
    add_code(r"\text{Compression\_Ratio} = \left( 1 - \frac{|W_{summary}|}{|W_{original}|} \right) \times 100\%")
    add_bullet("Silhouette Score [19]: Đo lường chất lượng thuật toán K-Means. Chỉ số chạy từ -1 đến 1. Điểm càng cao chứng tỏ các cụm chủ đề càng phân bổ tách biệt và sắc nét trong không gian 768 chiều:", "Chỉ số Nội tại (Intrinsic): ")
    add_code(r"\text{Silhouette} = \frac{b - a}{\max(a, b)}")
    add_bullet("Diversity Score (Độ đa dạng) [11]: Định lượng khả năng chống lặp ý của hệ thống. Nhóm tính bằng 1 trừ đi trung bình cộng độ tương đồng Cosine giữa toàn bộ các cặp câu được chọn. Điểm càng gần 1, các câu càng đa dạng ý nghĩa:", "Chỉ số Nội tại (Intrinsic): ")
    add_code(r"\text{Diversity} = 1 - \frac{2}{K(K-1)} \sum_{i=1}^{K-1} \sum_{j=i+1}^{K} \cos(\mathbf{v}_i, \mathbf{v}_j)")
