def write(doc, add_heading_1, add_heading_2, add_heading_3, add_p, add_bullet, add_code, style_table):
    add_heading_1("CHƯƠNG 4. PHƯƠNG PHÁP ĐỀ XUẤT (PROPOSED METHOD)")

    add_heading_2("4.1. Kiến trúc Tổng thể: Quy trình 2 Giai đoạn (Proposed 2-Stage Framework)")
    add_p("Khắc phục triệt để các nhược điểm của các phương pháp đi trước, đồ án thiết kế một kiến trúc Trí tuệ Nhân tạo đột phá vận hành trên Quy trình 2 giai đoạn (2-Stage Pipeline):")
    add_bullet("Giai đoạn 1 (Biểu diễn Ngữ nghĩa - Representation Learning): Sử dụng thuật toán ROUGE-1 Oracle Matching tự động dán nhãn hàng triệu cặp câu, sau đó tiến hành Supervised Fine-Tuning mô hình SBERT (Vietnamese Bi-Encoder) với hàm CosineSimilarityLoss để định hình lại hình thái học của không gian Vector.", bold_prefix="")
    add_bullet("Giai đoạn 2 (Lựa chọn Cân bằng - Diversity-Aware Selection): Vận hành trên môi trường Inference độc lập, các câu văn sau khi chuyển hóa thành Vector được đưa qua thuật toán Unsupervised K-Means Clustering để tạo K cụm chủ đề, tính điểm vị trí (Hybrid Centroid Scoring) và chạy màng lọc khử trùng lặp cuối cùng (Post-Filtering).", bold_prefix="")
    add_code("[ GIAI ĐOẠN 1: REPRESENTATION LEARNING ]        [ GIAI ĐOẠN 2: DIVERSITY-AWARE SELECTION ]\n ROUGE Oracle Matching ──► SBERT Fine-Tuning  ──► K-Means Clustering ──► Post-Filtering (θ=0.85)\n (Học Vector Biểu diễn Ngữ nghĩa Văn bản)        (Phân cụm Chủ đề con)    (Khử trùng lặp dư thừa)")

    add_heading_2("4.2. Giai đoạn 1: Representation Learning thông qua ROUGE-1 Oracle Matching")
    
    add_heading_3("4.2.1. Định nghĩa Thuật ngữ 'Oracle' trong Xử lý Ngôn ngữ Tự nhiên")
    add_p("Trong Khoa học Máy tính (Computer Science) và Lý thuyết Độ phức tạp tính toán, một máy 'Oracle' (Nhà tiên tri / Thực thể Hoàn hảo) là khái niệm hộp đen trừu tượng mang đáp án tối ưu tuyệt đối mà không thuật toán nào vượt qua được. Trong bài toán Tóm tắt trích xuất (Extractive Summarization), các bộ dữ liệu báo chí gốc (như CNN/DailyMail) chỉ cung cấp 2 trường văn bản: Toàn bộ Bài báo (Article) và Đoạn văn Tóm tắt do nhà báo tự viết tay (Human-written Abstractive Summary). Vì nhà báo tự viết tay, họ thường thay đổi từ vựng, đảo ngữ pháp, và KHÔNG HỀ dán nhãn rõ ràng \"tôi đã lấy câu số 3 và câu số 5 trong bài gốc\". Do đó, mô hình AI không có mục tiêu (Ground Truth Labels) để học.")
    add_p("Thuật toán ROUGE Oracle Extraction [Nallapati et al., 2016; Liu & Lapata, 2019] giải quyết bế tắc này bằng cách đóng vai 'người tìm đáp án lý tưởng'. Thuật toán này sẽ chạy vòng lặp vét cạn (Exhaustive Search), so sánh từng câu trong bài báo gốc với câu tóm tắt chuẩn, và chọn ra tập câu có điểm ROUGE tiệm cận nhất với bản tóm tắt chuẩn. Tập câu này được gọi là Pseudo Labels (Nhãn giả) hoặc Oracle Sentences, đóng vai trò là Ground Truth lý tưởng cho quá trình huấn luyện AI.")

    add_heading_3("4.2.2. Thuật toán ROUGE-1 Oracle Matching & Công thức Toán học")
    add_p("Hàm generate_oracle_extractive_pairs tự động tạo tập các cặp câu huấn luyện. Thay vì so sánh nguyên cả đoạn tóm tắt dài, thuật toán chia nhỏ bản tóm tắt của con người thành từng câu đơn lẻ (15 từ so với 15 từ). Cụ thể:")
    add_p("Công thức tính Precision (Độ chính xác - Bao nhiêu từ của câu bài báo khớp với câu tóm tắt):")
    add_code("Precision = |S_article ∩ S_reference| / |S_article|")
    add_p("Công thức tính Recall (Độ phủ - Bao nhiêu từ của câu tóm tắt được tìm thấy trong câu bài báo):")
    add_code("Recall = |S_article ∩ S_reference| / |S_reference|")
    add_p("Công thức Trung bình điều hòa (F1-Score):")
    add_code("ROUGE-1 F1 = 2 * (Precision * Recall) / (Precision + Recall)")

    add_p("Ví dụ Phân tích Từng bước Toán học (Step-by-step Execution):")
    add_bullet("Câu bài báo gốc (S_A): \"Trí tuệ nhân tạo đang phát triển rất nhanh tại Việt Nam trong năm nay.\" (14 từ).", "")
    add_bullet("Câu tóm tắt chuẩn (S_R): \"AI và trí tuệ nhân tạo phát triển mạnh tại Việt Nam.\" (12 từ).", "")
    add_bullet("Tiền xử lý & Tokenization: Loại bỏ Stopwords, chuẩn hóa chữ thường.")
    add_bullet("Tập từ trùng nhau (S_A ∩ S_R): {'trí', 'tuệ', 'nhân', 'tạo', 'phát', 'triển', 'tại', 'việt', 'nam'} (9 từ trùng).", "")
    add_bullet("Bước 1 (Precision): Precision = 9 / 14 = 0.642 (64.2%).", "")
    add_bullet("Bước 2 (Recall): Recall = 9 / 12 = 0.750 (75.0%).", "")
    add_bullet("Bước 3 (ROUGE-1 F1): F1 = 2 * (0.642 * 0.750) / (0.642 + 0.750) = 0.692 (69.2%).", "")

    add_p("Tại sao chọn ROUGE-1 thay vì ROUGE-2 hay ROUGE-L làm Nhãn? ROUGE-1 đo lặp unigrams, giúp bắt chặt các Thực thể (tên riêng, địa danh, con số) - linh hồn của báo chí. ROUGE-2 quá khắt khe, nhà báo chỉ cần đảo ngữ pháp (\"Phát triển mạnh AI\" thành \"AI phát triển mạnh\") là ROUGE-2 lập tức rớt về 0.0, khiến hệ thống loại nhầm câu ý chính.")

    add_heading_3("4.2.3. Chiến lược Phân cực Nhãn (Margin Binarization) & Toán học hàm Loss")
    add_p("Mục tiêu của hàm CosineSimilarityLoss là kéo Vector của 2 câu xích lại gần nhau (Cosine -> 1.0) hoặc đẩy ra xa nhau (Cosine -> 0.0). Tuy nhiên, nếu gán thẳng điểm F1 (như 0.38) vào mạng Neural, mô hình sẽ bị lấp lửng và không hội tụ.")
    add_p("Chiến thuật Margin Binarization Strategy (Bỏ Vùng Đệm) được áp dụng:")
    add_bullet("Cặp PULL (Nhãn Ý chính = 1.0): Lọc các câu bài báo có ROUGE-1 > 0.45. Hàm Loss ép Cosine = 1.0.", "")
    add_bullet("Cặp PUSH (Nhãn Phụ/Rác = 0.0): Lọc các câu bài báo có ROUGE-1 < 0.10. Hàm Loss ép Cosine = 0.0.", "")
    add_bullet("Vùng Đệm Không Tương Thích (0.10 <= ROUGE-1 <= 0.45): Bị xóa bỏ hoàn toàn khỏi bộ dữ liệu. Việc tạo ra Margin Gap (Khoảng trống Ranh giới) rất lớn giúp thuật toán K-Means ở Giai đoạn 2 dễ dàng tìm được mặt phẳng siêu phẳng cắt ngang dữ liệu mà không bị nhiễu.", "")

    add_heading_2("4.3. Huấn luyện Supervised Fine-Tuning & Tối ưu Thuật toán Học Sâu")
    add_p("Mô hình Tiếng Anh (all-mpnet-base-v2) và Tiếng Việt (vietnamese-bi-encoder) được Fine-Tune bằng Google Colab T4 GPU. Hệ thống sử dụng PyTorch DataLoader kết hợp trình tối ưu hóa (Optimizer) AdamW (Adam with Weight Decay) - một trong những thuật toán tối ưu tiên tiến nhất hiện nay, vượt qua SGD (Stochastic Gradient Descent) nhờ việc cập nhật Learning Rate động cho từng tham số và ngăn chặn hiện tượng quá khớp (Overfitting) bằng hằng số phạt L2 (Weight Decay = 1e-4).")
    add_p("Quá trình chia batch (batch_size=32) giúp vừa vặn VRAM (RAM GPU), và lệnh shuffle=True triệt tiêu hiện tượng lệch thứ tự (Order Bias), giúp AdamW hội tụ mượt mà.")
    add_p("Bảo vệ Tính Toàn Vẹn Học Thuật (Data Integrity): Quá trình huấn luyện chỉ nạp bài báo từ tập split='train', và việc đánh giá Benchmark tuyệt đối chỉ nạp trên tập split='test'. Rò rỉ dữ liệu (Data Leakage) được chặn 100%. Trọng số sau huấn luyện của Tiếng Việt được đẩy lên Hub toàn cầu: kttt294/vietnamese-sbert-finetuned.")

    add_heading_2("4.4. Chiến thuật Lấy mẫu Phân tầng Chất lượng Toán học (Quality-Aware Stratified Sampling)")
    add_p("Vấn đề: Nạp 100% 287,000 bài báo CNN vào SBERT sẽ gây ra thảm họa Quên Cục bộ (Catastrophic Forgetting) [Howard & Ruder, 2018], phá hủy hoàn toàn bộ trọng số ngôn ngữ tổng quát mà SBERT đã học từ 1 Tỷ cặp câu SNLI. Theo Reimers & Gurevych (2019), đồ thị hiệu năng Fine-tune có xu hướng tiệm cận (Asymptotic curve), chỉ sau 3,000 bài báo là ROUGE đi ngang.")
    add_p("Nhóm đề xuất giải pháp Lấy mẫu Phân tầng 3 Bộ Tiêu chuẩn:")
    add_bullet("1. Tiêu chuẩn Lọc Nhiễu Thô (Length-based Filter): Loại bỏ các bài tin vắn (< 8 câu) hoặc tóm tắt quá ngắn (< 2 câu) do không đủ thông tin để học kiến trúc báo chí Inverted Pyramid.")
    add_bullet("2. Tiêu chuẩn Mật độ Nén (Density Filter): Loại bỏ các bài mà (N_từ_tóm_tắt / N_từ_bài_gốc) > 0.40. Đây là những bài lỗi (nhà báo copy dán 50% thân bài thành đoạn summary), tạo ra Label Noise làm ô nhiễm mô hình.")
    add_bullet("3. Phân tầng Phân phối Chuẩn (Gaussian Stratification): Chia 3000 bài báo đều vào 3 tầng: Tầng ngắn (33%, 8-15 câu), Tầng trung bình (34%, 15-30 câu), Tầng dài (33%, >30 câu). Đảm bảo SBERT hội tụ tối ưu trên mọi độ dài văn bản.")

    add_heading_2("4.5. Giai đoạn 2: Lựa chọn Cân bằng thông qua Unsupervised K-Means Clustering")
    add_p("Ở môi trường thực tế (Inference Time), K-Means sẽ phân cụm tất cả N câu trong bài báo thành K chủ đề con. K-Means thực hiện thuật toán lặp Lloyd (Lloyd's Algorithm) bao gồm:")
    add_bullet("Bước 1: Khởi tạo K tâm cụm (Centroids) ngẫu nhiên bằng thuật toán k-means++ (tránh tụ cục bộ).")
    add_bullet("Bước 2: Gán từng vector câu vào Tâm cụm có Khoảng cách Euclid (Euclidean Distance) nhỏ nhất.")
    add_bullet("Bước 3: Cập nhật lại Tâm cụm bằng cách lấy tọa độ trung bình cộng (Mean) của các điểm trong cụm.")
    add_bullet("Bước 4: Lặp lại cho đến khi thuật toán hội tụ (Tâm cụm không dịch chuyển).")
    
    add_heading_3("4.5.1. Chứng minh Toán học: Sự Đồng nhất giữa Euclidean và Cosine Distance")
    add_p("Nhiều người lầm tưởng K-Means trong thư viện scikit-learn sử dụng khoảng cách Euclidean (Đường thẳng hình học) sẽ không phù hợp với Vector NLP yêu cầu tính góc Cosine (Độ tương đồng góc). Nhóm nghiên cứu trình bày bằng chứng toán học khẳng định chúng ĐỒNG NHẤT 100% nếu các Vector đã được chuẩn hóa (L2-Normalization), tức là độ dài ||u|| = ||v|| = 1:")
    add_p("Theo định lý bình phương hiệu 2 vector:")
    add_code("||u - v||^2 = ||u||^2 + ||v||^2 - 2(u . v)")
    add_p("Vì ||u|| = 1 và ||v|| = 1, nên ||u||^2 + ||v||^2 = 2. Hơn nữa, trên vector chuẩn hóa L2, tích vô hướng (u . v) chính là Cosine(u, v).")
    add_code("=> ||u - v||^2 = 2 - 2*cos(u, v) = 2*(1 - cos(u, v)) = 2 * CosineDistance")
    add_p("Kết luận: Tối thiểu hóa bình phương khoảng cách Euclidean trong K-Means của scikit-learn chính là cực đại hóa Cosine Similarity. Kết quả K-Means là hoàn toàn tương thích với không gian SBERT.")

    add_heading_3("4.5.2. Công thức Hybrid Centroid Scoring (Vị trí & Ngữ nghĩa)")
    add_p("Thay vì chỉ chọn câu gần Tâm cụm nhất (Centroid-based Summarization [Rossiello, 2017]), hệ thống kết hợp Luật suy giảm vị trí (Position Decay) lấy cảm hứng từ hệ thống MEAD kinh điển [Radev, 2004]:")
    add_code("Score(s_i) = CosineSim(s_i, Centroid) + lambda * (1 / sqrt(i+1))")
    add_p("Trong đó, i là số thứ tự câu trong bài (0-indexed). (1 / sqrt(i+1)) suy giảm dần (1.0 -> 0.707 -> 0.577 -> ...). Hệ số lambda=0.35 điều hòa toán học, giúp giữ lại các câu mở bài nhưng không hoàn toàn chèn ép thân bài.")

    add_heading_2("4.6. Chứng minh Toán học: Tính Không Âm (cos >= 0) và Hiện tượng Anisotropy")
    add_p("Một hiện tượng toán học kỳ lạ của mạng Transformer đó là Anisotropy (Tính không đẳng hướng) [Ethayarajh, ACL 2019; Li et al., EMNLP 2020]. Không gian vector 768 chiều của BERT không lấp đầy đều một quả cầu Hyper-sphere mà bị nén chặt vào một Nón dương cực hẹp (Narrow Positive Hyper-octant Cone).")
    add_p("Hệ quả là: Cosine Similarity giữa MỌI cặp câu văn bản tự nhiên (bất kể ngược nghĩa nhau) luôn ra một số không âm: cos >= 0.0. Giá trị âm (-1.0) hoàn toàn không tồn tại trong thực tế. Chính vì vậy, hàm CosineSimilarityLoss với nhãn Margin [0.0, 1.0] tương thích 100% với tính chất hình học của Transformer, ép cụm rác về mốc 0.0 thay vì -1.0 vô nghĩa.")

    add_heading_2("4.7. Khả năng Tổng quát hóa & Sự Độc lập (Model Generalization)")
    add_p("Liệu SBERT Fine-tuned có học thuộc lòng (Overfitting) văn phong của 1 tác giả cụ thể? Câu trả lời là KHÔNG, dựa trên 3 nguyên lý Khoa học dữ liệu:")
    add_bullet("1. Học Tín hiệu Cốt lõi (Semantic Invariants): Mô hình phân biệt được cấu trúc Sự kiện (5W1H) vs Trích dẫn cá nhân/Rác.")
    add_bullet("2. Trung hòa Thiên vị (Editorial Consensus): Tập huấn luyện chứa hàng nghìn tác giả từ các báo VnExpress, Tuổi Trẻ, Dân Trí. Bias cá nhân của một nhà báo bị triệt tiêu chéo bởi đám đông.")
    add_bullet("3. Lớp màng lọc Unsupervised K-Means ở Giai đoạn 2 hoạt động hoàn toàn trên thuật toán toán học vô hướng, không hề sử dụng tri thức tác giả.")

    add_heading_2("4.8. Thuật toán Dynamic Adaptive K & Post-Filtering (θ = 0.85)")
    add_p("Bản tóm tắt tự nhiên không bao giờ cố định 3 hay 5 câu. Hệ thống đề xuất Thuật toán K động:")
    add_code("K = round(N_sentences * alpha * scale)")
    add_p("Với alpha=0.25 (Nén cơ sở 25%), scale là hệ số tùy chọn: 0.6 (Brief), 1.0 (Medium), 1.6 (Detailed).")
    add_p("Khâu Post-Filtering (θ = 0.85) đóng vai trò lá chắn cuối cùng chống lại Lỗi Ranh giới Cụm (Cluster Boundary Leakage) và Hiện tượng Nhạy cảm Phủ định (Negation Sensitivity Problem). Transformer thường lầm tưởng 2 câu 'Giá xăng tăng mạnh' và 'Giá xăng KHÔNG tăng mạnh' là gần giống nhau (Cosine = 0.89) do trùng quá nhiều từ khóa. Màng lọc filter_redundant duyệt tuyến tính, khi phát hiện 2 câu có Cosine > 0.85, tự động xóa câu phía sau để triệt tiêu mâu thuẫn Logic.")
