def write(doc, add_heading_1, add_heading_2, add_heading_3, add_p, add_bullet, add_code, style_table):
    add_heading_1("CHƯƠNG 7. KẾT LUẬN VÀ HƯỚNG PHÁT TRIỂN")
    add_heading_2("7.1. Kết luận và Đánh giá Mục tiêu")
    add_p("Đồ án đã xuất sắc hoàn thành toàn bộ các mục tiêu lý thuyết và thực tiễn đã đề ra từ Chương 1. Bằng việc đi sâu vào bản chất toán học của mô hình Transformer, Đồ án đã giải quyết thành công bài toán Tóm tắt văn bản trích xuất song ngữ (Anh - Việt), vượt qua những giới hạn chí mạng của các mô hình kinh điển như Lead-3 và TextRank.")
    add_p("Thành quả Học thuật:")
    add_bullet("Chứng minh định lượng bằng dữ liệu thực nghiệm quy mô lớn về tính bắt buộc của Supervised Fine-Tuning đối với Tiếng Việt. ROUGE-1 đạt mốc ấn tượng ~47% trên tập thử nghiệm. Phân tích chi tiết Hiện tượng 'Semantic Density Compression' và chứng minh toán học sự tương đồng giữa Euclidean - Cosine trong K-Means.")
    add_bullet("Cống hiến cho cộng đồng: Mô hình Tiếng Việt đã được tối ưu hóa và xuất bản chính thức trên Hugging Face Model Hub tại kttt294/vietnamese-sbert-finetuned.")
    add_p("Thành quả Ứng dụng:")
    add_bullet("Kiến trúc phần mềm Singleton và Lazy Loading giúp thu gọn RAM, tích hợp Frontend React Vite mượt mà và đóng gói hoàn chỉnh bằng Docker Compose. Một AI Research Lab Project đã thực sự biến thành một Production-ready Software.")

    add_heading_2("7.2. Hạn chế của Dữ liệu Báo chí và Phản biện Tổng quát hóa (Cross-domain Generalization)")
    add_p("Xuyên suốt Đồ án, mục tiêu cốt lõi là xây dựng một hệ thống Tóm tắt Đa lĩnh vực (Domain-Agnostic). Tuy nhiên, quy trình Fine-tuning ở Giai đoạn 1 lại bắt buộc phải thực hiện trên tập dữ liệu báo chí (VietNews). Điều này dấy lên một lo ngại học thuật: Liệu mô hình có bị thiên kiến (bias) và chỉ tóm tắt tốt báo chí hay không?")
    add_p("Để phản biện lại luận điểm này, nhóm nghiên cứu xin đưa ra 3 lập luận vững chắc:")
    add_bullet("Sự khan hiếm Dữ liệu Tiếng Việt (Data Scarcity): Hiện tại, VietNews là bộ dữ liệu tóm tắt văn bản duy nhất của Tiếng Việt đạt tiêu chuẩn về quy mô (100,000+ bài) và chất lượng. Việc không thể tìm thấy các bộ dữ liệu quy mô lớn trong lĩnh vực Y tế, Pháp luật hay Tài chính bằng Tiếng Việt là một hạn chế khách quan của ngành NLP nước nhà, buộc chúng ta phải dùng báo chí làm 'bàn đạp' học ngữ nghĩa.")
    add_bullet("Khử nhiễu nhờ Kiến trúc Lai (Hybrid Architecture): Nếu sử dụng các mô hình SOTA Supervised Classification như BERTSumExt [3] hay MatchSum [4], việc huấn luyện trên báo chí sẽ biến mô hình thành 'kẻ học vẹt' cấu trúc Kim tự tháp ngược (chỉ biết lấy 3 câu đầu). Ngược lại, Đồ án sử dụng SBERT chỉ để Học Không gian Vector (Representation Learning), còn khâu trích xuất chọn câu lại giao phó hoàn toàn cho thuật toán K-Means (Unsupervised Zero-shot). K-Means không hề biết về vị trí câu hay cấu trúc bài báo lúc huấn luyện, do đó bảo toàn được khả năng Tóm tắt Đa lĩnh vực (Generalization) khi áp dụng vào Hợp đồng hay Báo cáo tài chính.")
    add_bullet("Điểm yếu Tương đồng của SOTA: Theo bài báo gốc, BERTSumExt [3] chỉ được thử nghiệm trên 3 tập báo chí (CNN/DM, NYT, XSum). Trong khi đó, MatchSum [4] có tham vọng đa lĩnh vực và đã thử nghiệm trên cả PubMed (Y tế) hay Reddit. TUY NHIÊN, để làm được điều đó, tác giả MatchSum phải huấn luyện lại mô hình bằng các tập dữ liệu Y tế/Mạng xã hội khổng lồ có sẵn nhãn của tiếng Anh. Đối với tiếng Việt, chúng ta hoàn toàn không có dữ liệu có nhãn cho các lĩnh vực này. Nếu ép các mô hình Học có giám sát mạnh (Strong Supervised Learning) như MatchSum học trên báo VietNews rồi áp dụng dự đoán Hợp đồng pháp lý (Zero-shot Cross-domain), chúng sẽ thất bại nặng nề do bị 'học vẹt' vị trí câu. Đó là lý do kiến trúc tách rời Học biểu diễn (SBERT) và Trích xuất không giám sát (K-Means) của Đồ án là giải pháp thực tiễn nhất cho môi trường Low-resource như tiếng Việt.")


    add_heading_2("7.3. Định hướng Phát triển Tương lai")
    add_bullet("Tóm tắt Đa phương thức (Multimodal Summarization): Kết hợp OCR (Nhận dạng chữ quang học) để đọc chữ từ biểu đồ, hình ảnh trong bài báo, hoặc tóm tắt bản ghi âm Podcast.")
    add_bullet("Lồng ghép LLMs thế hệ mới (Hybrid Extractive-Abstractive): Mặc dù Extractive có ưu điểm về tính xác thực, nhưng việc kết hợp với LLaMA 3 hoặc GPT-4 (qua API) để làm mượt các câu văn trích xuất (Smoothing) sẽ mang lại chất lượng xuất bản cao hơn.")
    add_bullet("Cá nhân hóa tin tức (Personalized News): Bổ sung Recommendation System dựa trên Lịch sử đọc của User, tự động lọc và tóm tắt theo chủ đề ưa thích của từng người.")
    add_bullet("Huấn luyện Đa lĩnh vực bằng Bách khoa toàn thư (Wikipedia): Mặc dù dữ liệu báo chí (CNN/DM, VietNews) vốn đã bao phủ một phổ chủ đề rất phong phú (Kinh tế, Y tế, Thể thao, Pháp luật cơ bản), định hướng tương lai là tiếp tục bổ sung tập dữ liệu bách khoa toàn thư như WikiSum (Wikipedia) vào quá trình Fine-tune. Đoạn mở đầu (Lead section) của mỗi bài viết Wikipedia thường được biên tập viên chắt lọc thành một bản tóm tắt hoàn hảo. Việc kết hợp thêm nguồn tri thức học thuật này sẽ giúp mô hình SBERT mở rộng tối đa không gian biểu diễn (Embedding Space), đạt được độ Tổng quát hóa (Generalization) toàn diện hơn nữa cho các văn bản mang tính chuyên môn sâu.")
